apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-depl
  template:
    metadata:
      labels:
        app: backend-depl
    spec:
      containers:
        - name: backend-depl
          image: rafin1998/rafin-blog-site:1.0
          ports:
            - containerPort: 6000
          env:
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: SECRET_KEY
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: API_KEY
            - name: POSTGRES_SERVER_NAME
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: POSTGRES_SERVER_NAME
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: POSTGRES_PASSWORD
            - name: APP_SETTINGS
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: APP_SETTINGS
            - name: FLASK_APP
              value: manage.py
